# Generated by Django 5.1.2 on 2024-11-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=7)),
                ('seats', models.PositiveSmallIntegerField()),
                ('seats_first_row', models.PositiveSmallIntegerField()),
                ('seats_reduced_mobility', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
