# Generated by Django 5.1.2 on 2024-11-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bus_bus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ten_ticket_pass', 'ten_ticket_pass'), ('ten_ticket_pass_multi_route', 'ten_ticket_pass_multi_route'), ('monthly_pass', 'monthly_pass'), ('monthly_pass_multi_route', 'monthly_pass_multi_route'), ('three_month_pass', 'three_month_pass'), ('four_month_pass', 'four_month_pass'), ('year_pass', 'year_pass')], max_length=50, unique=True)),
                ('max_uses', models.PositiveSmallIntegerField(null=True)),
                ('price', models.PositiveIntegerField(db_comment='Stored in cts')),
                ('is_multi_route', models.BooleanField(db_default=False)),
            ],
        ),
    ]
