# Generated by Django 5.1.2 on 2024-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_passtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtype',
            name='max_uses',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
