# Generated by Django 5.1.2 on 2024-11-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_passtype_max_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_travels_done', models.PositiveSmallIntegerField()),
                ('num_travels_uncompleted', models.PositiveSmallIntegerField()),
                ('purchased_datetime', models.DateTimeField(auto_now_add=True)),
                ('validity_date', models.DateField()),
                ('first_city', models.CharField(choices=[('M', 'Madrid'), ('B', 'Barcelona'), ('TO', 'Toledo'), ('BU', 'Burgos'), ('SO', 'Soria'), ('OV', 'Oviedo'), ('PO', 'Pontevedra')], max_length=2)),
                ('second_city', models.CharField(choices=[('M', 'Madrid'), ('B', 'Barcelona'), ('TO', 'Toledo'), ('BU', 'Burgos'), ('SO', 'Soria'), ('OV', 'Oviedo'), ('PO', 'Pontevedra')], max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
                ('pass_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.passtype')),
            ],
        ),
    ]
