# Generated by Django 5.1.2 on 2024-11-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
