# Generated by Django 5.1.2 on 2024-11-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('M', 'Madrid'), ('B', 'Barcelona'), ('TO', 'Toledo'), ('BU', 'Burgos'), ('SO', 'Soria'), ('OV', 'Oviedo'), ('PO', 'Pontevedra')], max_length=2)),
                ('destination', models.CharField(choices=[('M', 'Madrid'), ('B', 'Barcelona'), ('TO', 'Toledo'), ('BU', 'Burgos'), ('SO', 'Soria'), ('OV', 'Oviedo'), ('PO', 'Pontevedra')], max_length=2)),
                ('schedule', models.DateTimeField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.bus')),
            ],
        ),
    ]
