# Generated by Django 5.1.2 on 2024-11-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField(db_comment='Stored in cts', null=True)),
                ('purchase_datetime', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.travel')),
            ],
        ),
    ]
