# Generated by Django 5.1.2 on 2024-11-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seat_number', 'travel_id'), name='unique_seat_per_travel'),
        ),
    ]
