# Generated by Django 5.1.2 on 2024-11-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_ticket_unique_seat_per_travel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='travel_id',
            new_name='travel',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='bus_id',
            new_name='bus',
        ),
    ]
