# Generated by Django 5.1.2 on 2024-11-09 12:59

import booking.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_rename_customer_id_ticket_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seats_first_row',
            field=models.PositiveSmallIntegerField(validators=[booking.validators.validate_seats_first_row]),
        ),
        migrations.AlterField(
            model_name='travel',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.bus', unique_for_date='schedule'),
        ),
    ]
