# Generated by Django 5.1.2 on 2024-11-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_passtype_default_validity_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passtype',
            old_name='default_validity_days',
            new_name='validity_duration',
        ),
    ]
