# Generated by Django 5.1.2 on 2024-11-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_rename_default_validity_days_passtype_validity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passtype',
            name='validity_duration',
        ),
        migrations.AddField(
            model_name='passtype',
            name='days_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
