# Generated by Django 5.1.2 on 2024-11-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_passtype_validity_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passtype',
            old_name='days_duration',
            new_name='months_duration',
        ),
    ]
