# Generated by Django 5.1.2 on 2024-11-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_rename_days_duration_passtype_months_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='first_city',
            field=models.CharField(blank=True, choices=[('M', 'Madrid'), ('B', 'Barcelona'), ('TO', 'Toledo'), ('BU', 'Burgos'), ('SO', 'Soria'), ('OV', 'Oviedo'), ('PO', 'Pontevedra')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='second_city',
            field=models.CharField(blank=True, choices=[('M', 'Madrid'), ('B', 'Barcelona'), ('TO', 'Toledo'), ('BU', 'Burgos'), ('SO', 'Soria'), ('OV', 'Oviedo'), ('PO', 'Pontevedra')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
