# Generated by Django 5.1.2 on 2024-11-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_pass_first_city_alter_pass_second_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='pass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.passtype'),
        ),
    ]
