# Generated by Django 5.1.2 on 2024-11-09 19:39

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_pass_pass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.PositiveSmallIntegerField(validators=[booking.validators.validate_seats]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats_reduced_mobility',
            field=models.PositiveSmallIntegerField(validators=[booking.validators.validate_rm_seats]),
        ),
    ]
