# Generated by Django 5.1.2 on 2024-11-10 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_alter_bus_seats_alter_bus_seats_reduced_mobility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[A-Z]{2}[0-9]{2}', 'XXYY where X are letters and Y are numbers')]),
        ),
    ]
