# Generated by Django 5.1.2 on 2024-11-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_bus_bus_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birt_date',
            new_name='birth_date',
        ),
    ]
