# Generated by Django 5.1.2 on 2024-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_rename_birt_date_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(blank=True, db_comment='Stored in cts', null=True),
        ),
    ]
